### ISSUE TITLE
Support deploy Worlds scene to the same NAME with different wallets

### ISSUE THREAD

**Issue by pentreathm** [decentraland/worlds-content-server#38]
When there is a team behind a scene, several users may need to be able to upload content to the same DCL NAME. 
A system to allow different addresses to do these deployments is needed and could be created using a SMART contact that manages a list of allowed addresses per NAME. At the same time, the Worlds content server would run the needed validations against this contract and the ownership graphs

**Comment by eordano** [comment]
Can we have this by sending a partial AUTH CHAIN signature instead of a smart contract?

**Comment by marianogoldman** [comment]
Done
